server:
  port: ${LAVALINK_SERVER_PORT:2333}
  address: ${LAVALINK_SERVER_ADDRESS:0.0.0.0}

lavalink:
  server:
    password: ${LAVALINK_SERVER_PASSWORD:changeme}
    sources:
      youtube: false
      soundcloud: true
      bandcamp: false
      twitch: false
      vimeo: false
      http: true
      local: false
    bufferDurationMs: 400
    youtubePlaylistLoadLimit: 6
    playerUpdateInterval: 5
    trackStuckThresholdMs: 12000
    useSeekGhosting: true
    gc-warnings: true

plugins:
  - dependency: "dev.lavalink.youtube:youtube-plugin:${LAVALINK_YOUTUBE_PLUGIN_VERSION:1.11.5}"
    repository: "https://maven.lavalink.dev/releases"
  - dependency: "com.github.topi314.lavasrc:lavasrc-plugin:${LAVALINK_SPOTIFY_PLUGIN_VERSION:3.2.0}"
    repository: "https://maven.lavalink.dev/releases"

lavasrc:
  providers:
    - "ytsearch:%QUERY%"
    - "scsearch:%QUERY%"
  sources:
    spotify: true
    applemusic: false
    deezer: false
    yandexmusic: false
    flowerytts: false
    youtube: true
    soundcloud: true
  spotify:
    clientId: ${SPOTIFY_CLIENT_ID:}
    clientSecret: ${SPOTIFY_CLIENT_SECRET:}
    countryCode: "US"

logging:
  level:
    root: INFO
    lavalink: INFO
